# Table of Contents
* [Sorting](#sort)
* [Flexible Binary Operations](#flex)
* [Descriptive Statistics](#des)
* [Function Application](#func)
* [Reindexing and Altering Labels](#)

In [11]:
import sys #only needed to determine Python version number
import pandas as pd #this is how I usually import pandas
import numpy as np
import matplotlib.pyplot as plt
import matplotlib #only needed to determine Matplotlib version number

# Enable inline plotting
%matplotlib inline

In [36]:
def readData(location):
    try:
        if location.endswith('.txt') or location.endswith('.csv'):
            return pd.read_csv(location)
        elif location.endswith('.xlsx'):
            return pd.read_excel(location)
        else:
            raise TypeError
    except TypeError:
        print("invalid file type")
    except:
        print("other exceptions")

location = './dataset/Seasons_Stats.csv'        
players_all = readData(location) #since 1995
players_all = players_all.drop(columns=['Unnamed: 0', 'blanl', 'blank2'])
print(players_all.columns)
print(players_all.index)
players_all = players_all.loc[:, ['Year', 'Player', 'Tm', 'Pos', 'G', 'GS', 'PTS', 'FG%', '3P%', '2P%', 'FT%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'PF']]
players_season_2017 = players_all[(players_all['Year']==2017)]
top_scorers = players_season_2017.sort_values(by='PTS', ascending=False).head(20)
top_scorers

Index(['Year', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'PER', 'TS%',
       '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%',
       'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM', 'DBPM', 'BPM', 'VORP',
       'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%',
       'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV',
       'PF', 'PTS'],
      dtype='object')
RangeIndex(start=0, stop=24691, step=1)

,Year,Player,Tm,Pos,G,GS,PTS,FG%,3P%,2P%,FT%,TRB%,AST%,STL%,BLK%,TOV%,PF
24654,2017.0,Russell Westbrook,OKC,PG,81.0,81.0,2558.0,0.425,0.343,0.459,0.845,17.1,57.3,2.3,0.9,15.9,190.0
24306,2017.0,James Harden,HOU,PG,81.0,81.0,2356.0,0.440,0.347,0.530,0.847,12.2,50.7,2.0,1.0,19.5,215.0
24612,2017.0,Isaiah Thomas,BOS,PG,76.0,76.0,2199.0,0.463,0.379,0.528,0.909,4.4,32.6,1.4,0.4,10.7,167.0
24218,2017.0,Anthony Davis,NOP,C,75.0,75.0,2099.0,0.504,0.299,0.524,0.802,17.3,11.1,1.7,5.1,9.1,168.0
24625,2017.0,Karl-Anthony Towns,MIN,C,82.0,82.0,2061.0,0.542,0.367,0.582,0.832,19.4,13.2,1.0,2.9,11.3,241.0
24421,2017.0,Damian Lillard,POR,PG,75.0,75.0,2024.0,0.444,0.370,0.491,0.895,7.6,28.7,1.3,0.6,10.2,152.0
24226,2017.0,DeMar DeRozan,TOR,SG,74.0,74.0,2020.0,0.467,0.266,0.484,0.842,8.3,20.6,1.5,0.4,9.0,134.0
24216,2017.0,Stephen Curry,GSW,PG,79.0,79.0,1999.0,0.468,0.411,0.537,0.898,7.3,31.1,2.6,0.5,13.0,183.0
24365,2017.0,LeBron James,CLE,SF,74.0,74.0,1954.0,0.548,0.363,0.611,0.674,12.6,41.3,1.6,1.3,16.1,134.0
24206,2017.0,DeMarcus Cousins,TOT,C,72.0,72.0,1942.0,0.452,0.360,0.483,0.772,18.2,25.8,2.0,3.3,13.5,278.0
24658,2017.0,Andrew Wiggins,MIN,SF,82.0,82.0,1933.0,0.452,0.356,0.473,0.760,6.3,10.6,1.4,0.8,9.4,183.0
24414,2017.0,Kawhi Leonard,SAS,SF,74.0,74.0,1888.0,0.485,0.381,0.529,0.880,9.8,18.9,2.7,1.8,9.1,122.0
24443,2017.0,C.J. McCollum,POR,SG,80.0,80.0,1837.0,0.480,0.420,0.506,0.912,5.8,18.0,1.3,1.2,9.9,202.0
24115,2017.0,Giannis Antetokounmpo,MIL,SF,80.0,80.0,1832.0,0.521,0.272,0.563,0.770,14.3,26.6,2.3,4.7,13.3,246.0
24645,2017.0,Kemba Walker,CHO,PG,79.0,79.0,1830.0,0.444,0.399,0.476,0.847,6.2,29.1,1.6,0.7,9.5,119.0
24360,2017.0,Kyrie Irving,CLE,PG,72.0,72.0,1816.0,0.473,0.401,0.505,0.905,5.0,29.7,1.6,0.8,10.3,157.0
24175,2017.0,Jimmy Butler,CHI,SF,76.0,75.0,1816.0,0.455,0.367,0.477,0.865,9.0,24.8,2.6,0.9,9.3,112.0
24646,2017.0,John Wall,WAS,PG,78.0,78.0,1805.0,0.451,0.327,0.480,0.801,6.5,46.9,2.7,1.4,16.2,151.0
24137,2017.0,Bradley Beal,WAS,SG,77.0,77.0,1779.0,0.482,0.404,0.538,0.825,5.0,16.2,1.5,0.7,9.6,169.0
24278,2017.0,Paul George,IND,SF,75.0,75.0,1775.0,0.461,0.393,0.501,0.898,10.3,16.1,2.2,0.9,12.6,206.0

## Sorting <a name="sort"></a>

In [39]:
top_scorers.columns = pd.MultiIndex.from_tuples([
    ('Personal','Year'),('Personal','Name'),('Personal','Team'),('Personal','Pos'),
    ('Points','G'),('Points','GS'),('Points','PTS'),('Points','FG%'),('Points','3P%'),('Points','2P%'),('Points','FT%'),
    ('Mixed','TRB%'),('Mixed','AST%'),('Mixed','STL%'),('Mixed','BLK%'),
    ('Bad','TOV%'),('Bad','PF')
])
top_scorers.sort_values(by=[('Bad', 'PF'), ('Bad', 'TOV%')])

      Personal                                 Points                       \
          Year                   Name Team Pos      G    GS     PTS    FG%
24175   2017.0           Jimmy Butler  CHI  SF   76.0  75.0  1816.0  0.455
24645   2017.0           Kemba Walker  CHO  PG   79.0  79.0  1830.0  0.444
24414   2017.0          Kawhi Leonard  SAS  SF   74.0  74.0  1888.0  0.485
24226   2017.0          DeMar DeRozan  TOR  SG   74.0  74.0  2020.0  0.467
24365   2017.0           LeBron James  CLE  SF   74.0  74.0  1954.0  0.548
24646   2017.0              John Wall  WAS  PG   78.0  78.0  1805.0  0.451
24421   2017.0         Damian Lillard  POR  PG   75.0  75.0  2024.0  0.444
24360   2017.0           Kyrie Irving  CLE  PG   72.0  72.0  1816.0  0.473
24612   2017.0          Isaiah Thomas  BOS  PG   76.0  76.0  2199.0  0.463
24218   2017.0          Anthony Davis  NOP   C   75.0  75.0  2099.0  0.504
24137   2017.0           Bradley Beal  WAS  SG   77.0  77.0  1779.0  0.482
24658   2017.0         Andrew Wiggins  MIN  SF   82.0  82.0  1933.0  0.452
24216   2017.0          Stephen Curry  GSW  PG   79.0  79.0  1999.0  0.468
24654   2017.0      Russell Westbrook  OKC  PG   81.0  81.0  2558.0  0.425
24443   2017.0          C.J. McCollum  POR  SG   80.0  80.0  1837.0  0.480
24278   2017.0            Paul George  IND  SF   75.0  75.0  1775.0  0.461
24306   2017.0           James Harden  HOU  PG   81.0  81.0  2356.0  0.440
24625   2017.0     Karl-Anthony Towns  MIN   C   82.0  82.0  2061.0  0.542
24115   2017.0  Giannis Antetokounmpo  MIL  SF   80.0  80.0  1832.0  0.521
24206   2017.0       DeMarcus Cousins  TOT   C   72.0  72.0  1942.0  0.452

                           Mixed                   Bad
         3P%    2P%    FT%  TRB%  AST% STL% BLK%  TOV%     PF
24175  0.367  0.477  0.865   9.0  24.8  2.6  0.9   9.3  112.0
24645  0.399  0.476  0.847   6.2  29.1  1.6  0.7   9.5  119.0
24414  0.381  0.529  0.880   9.8  18.9  2.7  1.8   9.1  122.0
24226  0.266  0.484  0.842   8.3  20.6  1.5  0.4   9.0  134.0
24365  0.363  0.611  0.674  12.6  41.3  1.6  1.3  16.1  134.0
24646  0.327  0.480  0.801   6.5  46.9  2.7  1.4  16.2  151.0
24421  0.370  0.491  0.895   7.6  28.7  1.3  0.6  10.2  152.0
24360  0.401  0.505  0.905   5.0  29.7  1.6  0.8  10.3  157.0
24612  0.379  0.528  0.909   4.4  32.6  1.4  0.4  10.7  167.0
24218  0.299  0.524  0.802  17.3  11.1  1.7  5.1   9.1  168.0
24137  0.404  0.538  0.825   5.0  16.2  1.5  0.7   9.6  169.0
24658  0.356  0.473  0.760   6.3  10.6  1.4  0.8   9.4  183.0
24216  0.411  0.537  0.898   7.3  31.1  2.6  0.5  13.0  183.0
24654  0.343  0.459  0.845  17.1  57.3  2.3  0.9  15.9  190.0
24443  0.420  0.506  0.912   5.8  18.0  1.3  1.2   9.9  202.0
24278  0.393  0.501  0.898  10.3  16.1  2.2  0.9  12.6  206.0
24306  0.347  0.530  0.847  12.2  50.7  2.0  1.0  19.5  215.0
24625  0.367  0.582  0.832  19.4  13.2  1.0  2.9  11.3  241.0
24115  0.272  0.563  0.770  14.3  26.6  2.3  4.7  13.3  246.0
24206  0.360  0.483  0.772  18.2  25.8  2.0  3.3  13.5  278.0

In [44]:
top_scorers = players_season_2017.sort_values(by='PTS', ascending=False).head(20)
top_scorers.sort_index(ascending=False)
top_scorers.sort_values(by=['FG%', '3P%', '2P%'], ascending=False)
top_scorers['TOV%'].nlargest(3) #method of series
top_scorers['TOV%'].nsmallest(3)

24226    9.0
24218    9.1
24414    9.1
Name: TOV%, dtype: float64

## Flexible Binary Operations <a name="flex"></a>

In [ ]:
#df.add(), sub(), mul(), divmod()

In [35]:
#df.eq(df2), ne(), gt(), lt(), le(), ge()

In [57]:
#test if a pandas object is empty
top_scorers.empty
pd.DataFrame(columns=list('ABC')).empty
#Is there a top scorer can reach 2000+ points while maintaining a 30%+ 3-ptr
((top_scorers['PTS'] > 2000) & (top_scorers['3P%'] > 0.3)).any()
#Do all players reach 1500+ points and 40% field goals 
((top_scorers['PTS'] > 1500) & (top_scorers['FG%'] > 0.4)).all()

True

In [60]:
#compare if objects are equivalent
#Notice that the boolean DataFrame df+df == df*2 contains some False values! That is because NaNs do not compare as equals:
df = pd.DataFrame(data=[[np.nan, 1],[2, np.nan]])
print(np.nan == np.nan)
print((df+df).equals(df*2))
df

False
True

     0    1
0  NaN  1.0
1  2.0  NaN

In [64]:
#combining overlapping data sets
df1 = pd.DataFrame({
    'col1':[1,np.nan,3,4,np.nan],
    'col2':[np.nan,np.nan,np.nan,9,10],
})

df2 = pd.DataFrame({
    'col1':[np.nan,np.nan,3,4,5],
    'col2':[6,7,8,np.nan,np.nan],
})

df1.combine_first(df2)

df1 = pd.DataFrame({'col1': [0, 0], 'col2': [4, 4]})
df2 = pd.DataFrame({'col1': [1, 1], 'col2': [3, 3]})
#Function that takes two series as inputs and return a Series or a scalar
combiner = lambda s1, s2: s1 if s1.sum() < s2.sum() else s2
df1.combine(df2, combiner)

   col1  col2
0     0     3
1     0     3

## Descriptive Statistics <a name='des'></a>

In [70]:
top_scorers['AST%'].describe()
top_scorers['Player'].describe() #non-numerical
top_scorers.describe(include='object') #all, number

              Player   Tm Pos
count             20   20  20
unique            20   16   4
top     LeBron James  MIN  PG
freq               1    2   8

In [77]:
#index of min,max values
top_scorers['FG%'].idxmax()
top_scorers.loc[24365, :]

Year              2017
Player    LeBron James
Tm                 CLE
Pos                 SF
G                   74
GS                  74
PTS               1954
FG%              0.548
3P%              0.363
2P%              0.611
FT%              0.674
TRB%              12.6
AST%              41.3
STL%               1.6
BLK%               1.3
TOV%              16.1
PF                 134
Name: 24365, dtype: object

In [82]:
#value counts(histogramming)/mode
print(top_scorers['Tm'].value_counts())
print(top_scorers['Tm'].mode())
print(top_scorers['Pos'].value_counts())
print(top_scorers['Pos'].mode())

MIN    2
CLE    2
WAS    2
POR    2
TOR    1
BOS    1
HOU    1
IND    1
OKC    1
NOP    1
CHO    1
GSW    1
MIL    1
CHI    1
TOT    1
SAS    1
Name: Tm, dtype: int64
0    CLE
1    MIN
2    POR
3    WAS
dtype: object
PG    8
SF    6
SG    3
C     3
Name: Pos, dtype: int64
0    PG
dtype: object

In [89]:
#Continuous values can be discretized using the cut() (bins based on values) and qcut() (bins based on sample quantiles) functions
factor = pd.cut(top_scorers['FT%'], 4)
factor = pd.cut(top_scorers['FT%'], [0.6, 0.7, 0.8, 0.9, 1])
factor.value_counts()
factor = pd.qcut(top_scorers['FT%'], [0, .25, .5, .75, 1])
factor

24654    (0.802, 0.846]
24306    (0.846, 0.896]
24612    (0.896, 0.912]
24218    (0.802, 0.846]
24625    (0.802, 0.846]
24421    (0.846, 0.896]
24226    (0.802, 0.846]
24216    (0.896, 0.912]
24365    (0.673, 0.802]
24206    (0.673, 0.802]
24658    (0.673, 0.802]
24414    (0.846, 0.896]
24443    (0.896, 0.912]
24115    (0.673, 0.802]
24645    (0.846, 0.896]
24360    (0.896, 0.912]
24175    (0.846, 0.896]
24646    (0.673, 0.802]
24137    (0.802, 0.846]
24278    (0.896, 0.912]
Name: FT%, dtype: category
Categories (4, interval[float64]): [(0.673, 0.802] < (0.802, 0.846] < (0.846, 0.896] < (0.896, 0.912]]

## Function Application <a name="func"></a>
> To apply your own or another library’s functions to pandas objects, you should be aware of the three methods below. The appropriate method to use depends on whether your function expects to operate on an entire DataFrame or Series, row- or column-wise, or elementwise
>
>1.Tablewise Function Application: pipe()  
2.Row or Column-wise Function Application: apply()  
3.Aggregation API: agg() and transform()  
4.Applying Elementwise Functions: applymap()

In [117]:
#row or column-wise function application
def applyInRow(row):
    return (row['TOV%']+row['PF'])
applyInCol = lambda col: col.mean()

top_scorers.apply(applyInRow, axis=1)
top_scorers.loc[:, ['PTS', 'PF']].apply(applyInCol, axis=0)

PTS    1976.15
PF      176.45
dtype: float64

In [101]:
#aggregating with multiple functions
top_scorers.loc[:, ['PTS', 'PF']].agg(['sum', 'mean'])

           PTS       PF
sum   39523.00  3529.00
mean   1976.15   176.45

In [152]:
#transforming with multiple functions
functions = {
    'PTS': [lambda x: x-x.mean(), lambda x: x-x%100],
    'FG%': lambda x: 1-x
}
#'minus_mean': (lambda x: x-x.mean())
top_scorers.transform(functions)

           PTS               FG%
      <lambda> <lambda> <lambda>
24654   581.85   2500.0    0.575
24306   379.85   2300.0    0.560
24612   222.85   2100.0    0.537
24218   122.85   2000.0    0.496
24625    84.85   2000.0    0.458
24421    47.85   2000.0    0.556
24226    43.85   2000.0    0.533
24216    22.85   1900.0    0.532
24365   -22.15   1900.0    0.452
24206   -34.15   1900.0    0.548
24658   -43.15   1900.0    0.548
24414   -88.15   1800.0    0.515
24443  -139.15   1800.0    0.520
24115  -144.15   1800.0    0.479
24645  -146.15   1800.0    0.556
24360  -160.15   1800.0    0.527
24175  -160.15   1800.0    0.545
24646  -171.15   1800.0    0.549
24137  -197.15   1700.0    0.518
24278  -201.15   1700.0    0.539

In [121]:
#applying elementwise functions
#methods applymap() on DataFrame and analogously map() on Series
acronym_to_fullname = {
    'PG':'point guard',
    'SG':'shooting guard',
    'PF':'power forward',
    'SF':'small forward',
    'C':'center'
}
top_scorers.Pos.map(acronym_to_fullname)

24654       point guard
24306       point guard
24612       point guard
24218            center
24625            center
24421       point guard
24226    shooting guard
24216       point guard
24365     small forward
24206            center
24658     small forward
24414     small forward
24443    shooting guard
24115     small forward
24645       point guard
24360       point guard
24175     small forward
24646       point guard
24137    shooting guard
24278     small forward
Name: Pos, dtype: object

In [143]:
points = top_scorers.loc[:,['Tm', 'PTS', 'FG%', '3P%', '2P%']]
gb_team = points.groupby('Tm')
print(gb_team.PTS.transform('sum')) #index is the same as original dataframe
print(gb_team.PTS.sum()) #index by group
print(gb_team.PTS.agg('mean')) #index by group

24654    2558.0
24306    2356.0
24612    2199.0
24218    2099.0
24625    3994.0
24421    3861.0
24226    2020.0
24216    1999.0
24365    3770.0
24206    1942.0
24658    3994.0
24414    1888.0
24443    3861.0
24115    1832.0
24645    1830.0
24360    3770.0
24175    1816.0
24646    3584.0
24137    3584.0
24278    1775.0
Name: PTS, dtype: float64
Tm
BOS    2199.0
CHI    1816.0
CHO    1830.0
CLE    3770.0
GSW    1999.0
HOU    2356.0
IND    1775.0
MIL    1832.0
MIN    3994.0
NOP    2099.0
OKC    2558.0
POR    3861.0
SAS    1888.0
TOR    2020.0
TOT    1942.0
WAS    3584.0
Name: PTS, dtype: float64
Tm
BOS    2199.0
CHI    1816.0
CHO    1830.0
CLE    1885.0
GSW    1999.0
HOU    2356.0
IND    1775.0
MIL    1832.0
MIN    1997.0
NOP    2099.0
OKC    2558.0
POR    1930.5
SAS    1888.0
TOR    2020.0
TOT    1942.0
WAS    1792.0
Name: PTS, dtype: float64

## Reindexing and Altering Labels